# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_16 ];
      }
      ''
        # workaround https://codeberg.org/ziglang/zig/issues/31866
        # https://github.com/Cloudef/zig2nix/issues/54
        mkdir "$TMPDIR/src" "$TMPDIR/cache" "$TMPDIR/cache/tmp"
        touch "$TMPDIR/src/build.zig"
        hash="$(cd "$TMPDIR/src" && zig fetch --global-cache-dir "$TMPDIR/cache" ${artifact})"
        mkdir "$out"
        tar zxvf "$TMPDIR/cache/p/$hash.tar.gz" --directory "$out/" --strip-components=1
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
  # The packages, as real directories holding symlinked files, rather than as
  # a farm of symlinked directories.
  #
  # Zig runs a dependency's own build steps with the working directory set to
  # that dependency, and points at the program to run with a path counted in
  # directories up from there. Through a symlink the two disagree: Zig counts
  # from `<farm>/<package>/`, four directories below the root, while the kernel
  # resolves the working directory to `/nix/store/<hash>`, which is three, so
  # the path lands one short of where the program is.
  #
  # It works anyway when the build directory is `/build`, because the sum then
  # overshoots into the root and going above the root stays there. It fails
  # when the build directory is under `/nix/var/nix/builds`, which is where Nix
  # puts it when the sandbox is off. Real directories make the two depths
  # agree, so it works either way.
  #
  # The files have to be real as well, which is the expensive part and cannot
  # be avoided. `--symbolic-link` would leave them pointing into each
  # dependency's own store path, so that the farm is a few megabytes rather
  # than a second copy of every dependency -- but Zig's
  # `installHeadersDirectory` walks the directory and copies only the entries
  # whose kind is `.file`. Symlinked headers are skipped without a word, and
  # the first thing to include one fails with `'dcimgui.h' not found`.
  #
  # `--link` is not the way out. A hard link into a Nix output is a file the
  # builder did not create: inside the Linux sandbox the store is a separate
  # mount and `link` fails with `Invalid cross-device link`, while on Darwin it
  # succeeds and leaves root-owned files in the output, which Nix refuses while
  # canonicalising with `invalid ownership on file`.
  #
  # So it is a real copy, with `--reflink=auto` to share the blocks on a
  # filesystem that can. `nix store optimise` recovers the duplication after
  # the fact, hard-linking identical files across the store, which is the
  # store's own business to do and not a build's.
  copyFarm =
    farm: entries: pathDependencyPackages:
    runCommandLocal farm
      {
        # The packages whose own manifest declares a dependency by `.path`.
        # Zig 0.16.0 cannot build these through `zig build --system`: it spins
        # in userspace forever, because a `.path` dependency's hash is computed
        # against the system package directory during the fetch and against the
        # real global cache afterwards, and in that mode the two disagree. A
        # package that wants `--system` copies each of these into its build
        # root and passes `--fork=`; see the README.
        passthru = { inherit pathDependencyPackages; };
      }
      ''
        mkdir -p "$out"
        cp --recursive --reflink=auto --dereference --no-preserve=mode \
          ${linkFarm farm entries}/. "$out/"
      '';
in
copyFarm name
  [
    {
      name = "N-V-__8AAOgqbADacob-q2_DMQlmgaG4xKHRuW-6PJ4oJzMZ";
      path = fetchZigArtifact {
        name = "fontconfig";
        url = "https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/2.18.3/fontconfig-2.18.3.tar.xz";
        hash = "sha256-T3tVSjjN94wDP2ZsiHHzdJ4UoJT2Wgf2MMke0LQ9NeM=";
        unpack = false;
      };
    }
    {
      name = "gobject-0.3.2-Skun7F6HogCMynX2JqeSHS7xr-8pK4ob-qRFIcEasVi3";
      path = fetchZigArtifact {
        name = "gobject";
        url = "https://deps.files.ghostty.org/gobject-2026-07-28-36-1.tar.zst";
        hash = "sha256-dyCfm2XjiAk30zccjD6AgKFBdE7IRsJuoqnscfvnWSQ=";
        unpack = true;
      };
    }
    {
      name = "known_folders-0.0.0-Fy-PJiDLAAB98m3uYUzatrTb2mO2fpvwx2zpSroEtfbO";
      path = fetchZigArtifact {
        name = "known_folders";
        url = "https://github.com/ziglibs/known-folders/archive/6da0d0c41b78b9ed2d34fa364fcb81b5ebece6c4.tar.gz";
        hash = "sha256-F17Ivvsyyla2CBIh+kImc1O3AtD2yTDAGamzMVbVzuw=";
        unpack = true;
      };
    }
    {
      name = "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA";
      path = fetchZigArtifact {
        name = "uucode_git";
        url = "git+https://github.com/jacobsandlund/uucode#2826a37a4562284fdacd8fa029d49509cc9bffcd";
        hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
        unpack = true;
      };
    }
    {
      name = "uucode-0.2.0-ZZjBPuuFVgC8YZ8eld4fOKsZANLIhTFMzULQxhkLi1C7";
      path = fetchZigArtifact {
        name = "uucode_zip";
        url = "https://github.com/jacobsandlund/uucode/archive/9d55524551411b493cca41ca06363625d90aff1e.zip";
        hash = "sha256-KZbp/0dlJc5BdxM19ZOXH74WEjEilTvzie/BjT1aYvw=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA";
      path = fetchZigArtifact {
        name = "wayland_protocols";
        url = "https://deps.files.ghostty.org/N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA.tar.gz";
        hash = "sha256-3S3xSrX0EDgleq7cxLX7msDuAY8/D5SvkJcCjmDTMiM=";
        unpack = false;
      };
    }
  ]
  [
  ]
