# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    "datetime-0.0.1-6-va78-AQgA0_OvOrxeem7LnZqCmkjL3AkD9XeT81C4l" = fetchZigGit {
      name = "datetime";
      url = "https://git.jcollie.dev/jeff/zig-datetime.git";
      rev = "b1d225e0548572c88c41a8b551b8397e5e168412";
      hash = "sha256-PT1j9g9mLRusAf/y+BRfJtCj7FSW0z7nEdHjWkB6V8o=";
    };
    "fluent-0.1.0-N_WW89PZcABO-GT7Whp6v-AHIGdyypS354Gzy660ujta" = fetchZigGit {
      name = "fluent";
      url = "https://git.jcollie.dev/jeff/zig-fluent.git";
      rev = "93101b427f76619d14cb8d433afc507fd3af0d02";
      hash = "sha256-1YHOwuhm0goNBXs2pE+WWMPeqSaPTeTBTxqwlQRFmB8=";
    };
    "N-V-__8AAOgqbADacob-q2_DMQlmgaG4xKHRuW-6PJ4oJzMZ" = fetchzip {
      name = "fontconfig";
      url = "https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/2.18.3/fontconfig-2.18.3.tar.xz";
      hash = "sha256-fAe2C2MdhrVb12K8LBaUPU/OyWpulHpMsnarkuLHWS4=";
    };
    "gobject-0.3.2-Skun7F6HogCMynX2JqeSHS7xr-8pK4ob-qRFIcEasVi3" = fetchzip {
      name = "gobject";
      url = "https://deps.files.ghostty.org/gobject-2026-07-28-36-1.tar.zst";
      hash = "sha256-dyCfm2XjiAk30zccjD6AgKFBdE7IRsJuoqnscfvnWSQ=";
      nativeBuildInputs = [ zstd ];
    };
    "known_folders-0.0.0-Fy-PJiDLAAB98m3uYUzatrTb2mO2fpvwx2zpSroEtfbO" = fetchzip {
      name = "known_folders";
      url = "https://github.com/ziglibs/known-folders/archive/6da0d0c41b78b9ed2d34fa364fcb81b5ebece6c4.tar.gz";
      hash = "sha256-F17Ivvsyyla2CBIh+kImc1O3AtD2yTDAGamzMVbVzuw=";
    };
    "N-V-__8AABybDwDd46ZHFqBjb0twea7p9vwNzdSzUHFwA55f" = fetchurl {
      url = "https://data.iana.org/time-zones/releases/tzcode2026d.tar.gz";
      hash = "sha256-L1yff+Kea4y4Y1g2Z4hLjOF7CkhTVaBUtZHGvfzYF5E=";
    };
    "N-V-__8AAFiAFQDNovBNmFwF3hznlSfpY7KwAN3Jy7rhie29" = fetchurl {
      url = "https://data.iana.org/time-zones/releases/tzdata2026d.tar.gz";
      hash = "sha256-DLKqjjM8PcBJutxCoMYfIZh7jNROEH+pALrXZKrMd2c=";
    };
    "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA" = fetchZigGit {
      name = "uucode_git";
      url = "https://github.com/jacobsandlund/uucode";
      rev = "2826a37a4562284fdacd8fa029d49509cc9bffcd";
      hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
    };
    "uucode-0.2.0-ZZjBPuuFVgC8YZ8eld4fOKsZANLIhTFMzULQxhkLi1C7" = fetchzip {
      name = "uucode_zip";
      url = "https://github.com/jacobsandlund/uucode/archive/9d55524551411b493cca41ca06363625d90aff1e.zip";
      hash = "sha256-KZbp/0dlJc5BdxM19ZOXH74WEjEilTvzie/BjT1aYvw=";
    };
    "N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA" = fetchzip {
      name = "wayland_protocols";
      url = "https://deps.files.ghostty.org/N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA.tar.gz";
      hash = "sha256-vD7Nj9iLeS52Et3gcX1m9Zmp05A+VV3J3hkPcM11YEQ=";
    };
  };

  # The packages whose own manifest declares a dependency by `.path`. Zig
  # 0.16.0 cannot build these through `zig build --system`: it spins in
  # userspace forever, because a `.path` dependency's hash is computed against
  # the system package directory during the fetch and against the real global
  # cache afterwards, and in that mode the two disagree. A package that wants
  # `--system` copies each of these into its build root and passes `--fork=`;
  # see the README.
  pathDependencyPackages = [
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what
# `zig build --system` wants.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_16 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Each package gets a directory of its own to work in, since `zig fetch`
    # leaves what it unpacked in `zig-pkg/` under the directory it ran in.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work/src" "$work/cache/tmp"
      # workaround https://codeberg.org/ziglang/zig/issues/31866
      # https://github.com/Cloudef/zig2nix/issues/54
      touch "$work/src/build.zig"
      # `zig fetch` recompresses every package into `p/` at gzip level 9 for
      # its own cache, which is nearly all of its time and of no use here.
      # With `p` a file rather than a directory that step fails at once --
      # Zig warns, and carries on -- and the package is left in `zig-pkg/`.
      touch "$work/cache/p"

      local hash
      if ! hash="$(cd "$work/src" && zig fetch --global-cache-dir "$work/cache" "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      mv "$work/src/zig-pkg/$1" "$out/$1"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
