# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_17,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    # @packages@
  };

  # The packages whose own manifest declares a dependency by `.path`, which
  # Zig 0.16.0 cannot build through `zig build --system`. Listed here too so
  # that every version's expression offers the same things; see the README.
  pathDependencyPackages = [
    # @pathDependencyPackages@
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what
# `zig build --system` wants.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_17 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Zig 0.17 runs `zig fetch` in a build runner it compiles into the global
    # cache the first time, which takes a minute or more. Every package shares
    # one cache, then, and it is compiled once here before they are fetched
    # several at a time, rather than by each of them at once.
    export ZIG_GLOBAL_CACHE_DIR="$TMPDIR/cache"
    mkdir -p "$ZIG_GLOBAL_CACHE_DIR"
    zig fetch --help >/dev/null

    # Without `--save`, which wants a project to save into, Zig 0.17 unpacks
    # nothing where it can be found: what it keeps is `p/<hash>.tar.gz` in
    # the global cache, the package filtered by its manifest's `.paths` under
    # a single directory named by its hash. Unpacking that gives the
    # directory `zig build --system` wants.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work"

      local hash
      if ! hash="$(cd "$work" && zig fetch "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      tar -xzf "$ZIG_GLOBAL_CACHE_DIR/p/$1.tar.gz" -C "$out"
      rm -f "$ZIG_GLOBAL_CACHE_DIR/p/$1.tar.gz"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    # `-r` because otherwise xargs runs `unpack` once, with no arguments, when
    # there are no packages at all, and the build fails.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -r -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
