# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_15,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    # @packages@
  };

  # The packages whose own manifest declares a dependency by `.path`, which
  # Zig 0.16.0 cannot build through `zig build --system`. Listed here too so
  # that the two versions' expressions offer the same things; see the README.
  pathDependencyPackages = [
    # @pathDependencyPackages@
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what Zig
# wants in its global cache's `p/`, or from `zig build --system`.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_15 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Each package gets a cache of its own to unpack into, so that several
    # can be unpacked at once. Zig 0.15 leaves one in `p/<hash>`.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work/cache"

      local hash
      if ! hash="$(cd "$work" && zig fetch --global-cache-dir "$work/cache" "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      mv "$work/cache/p/$1" "$out/$1"
      chmod 755 "$out/$1"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    # `-r` because otherwise xargs runs `unpack` once, with no arguments, when
    # there are no packages at all, and the build fails.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -r -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
