name: Close Pull Request

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448 # v3.1.2
        with:
          comment: "We do not accept PRs on GitHub, please submit them here: https://codeberg.org/jcollie/zon2nix"
